/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

// author: Steven Dellamore
// date: 2020-2-22
// version: 1.0.0

#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <string>
#include <cctype>
#include <list>
#include <sys/stat.h>
#include <unistd.h>
#include <functional>
#include <map>
#include <sstream>
#include <iterator>
#include <string>

template <typename T, typename U, typename G, typename H >
int maxoffour( T a, U b, G c, H d ) {
    return int ( std::max( std::max( a ,b ), std::max( c, d ) ) );
}

int main() {
    maxoffour(1,2,3,4);
}