/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */



int main() {
    // x @TODO
    int x = 5;
    std::cout << x;
    std::cout << x << std::endl;

    std::cout << x << "Hello";
    std::cout << x << "hello" << std::endl;

    // y @TODO
    int y = 6;
    
    std::cout << "x: " << x << " y: " << y;
    std::cout << "x: " << x << " y: " << y << std::endl;

    std::cout << "Hello " << "My " << "Name " << "Is " << "John " << "Doe\n";
    std::cout << "Hello " << "My " << "Name " << "Is " << "John " << "Doe" << std::endl;
}