/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

class object {

}

int main() {
    // a @TODO
    int a;
    // b @TODO
    int b = 5;
    // c @TODO
    auto c = 5+5*5;
    // d @TODO
    auto d = "Hello world";
    // e @TODO
    auto e = object();
}