/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

int main() {
    auto vec = std::vector< int >();
    vec.push_back(1); // pushing 1 onto vec
}