/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

int main() {
    auto vec = std::vector< int >();
    auto vec1 = std::vector< std::string >();
    auto vec2 = std::vector< bool >();
}