/* This file is auto generated by C-Sugar @author Steven Dellamore 
URL = https://github.com/Dellamoresteven/C-Sugar */

int main() {
    auto vec = std::vector< int >();
    vec.push_back(1); // pushing 1 onto vec
    vec.push_back(2); // pushing 2 onto vec
    vec.push_back(3); // pushing 3 onto vec
    vec.push_back(4); // pushing 4 onto vec
    vec.push_back(5); // pushing 5 onto vec
}